format = """
$directory\
$git_branch\
$git_status\
$git_state\
$fill\
$python\
$dotnet\
$nodejs\
$line_break\
$character"""

[fill]
symbol = ' '

[git_branch]
format='[$symbol$branch(:$remote_branch)]($style)'

[character] 
success_symbol = '[Î»](bold green)'

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
# pyenv_version_name=true
# pyenv_prefix=""

[nodejs]
format = '[${symbol}(${version})]($style)'
version_format='${raw}'

[dotnet]
format = '[${symbol}(${version})]($style)'
version_format='${raw}'
